# coding: utf-8

"""
    Telstra SMS Messaging API

    The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator. It also allows your application to track the delivery status of both sent and received SMS messages. 

    OpenAPI spec version: 2.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.sms_api import SMSApi


class TestSMSApi(unittest.TestCase):
    """ SMSApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.sms_api.SMSApi()

    def tearDown(self):
        pass

    def test_messages_sms_incoming(self):
        """
        Test case for messages_sms_incoming

        Retrieve the unread incoming SMS messages
        """
        pass

    def test_messages_sms_send(self):
        """
        Test case for messages_sms_send

        Send an SMS to a Australian or International mobile phone.
        """
        pass

    def test_messages_sms_status(self):
        """
        Test case for messages_sms_status

        Retrieve the status of a single outgoing SMS message.
        """
        pass


if __name__ == '__main__':
    unittest.main()
